version: '3.4'

services:
  redis_server:
    image: redis:5
    ports:
      - "6379:6379"

  parser:
    env_file:
      - ./config/docker.env
    build: ./parser
    image: "transit_data_access/parser:latest"
    depends_on:
      - redis_server
    ports:
      - "45654:45654"
    deploy:
      resources:
       limits:
        memory: 512M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 4
        window: 10s

  web_server:
    env_file:
      - ./config/docker.env
    build: ./web_server
    image: "transit_data_access/web_server:latest"
    depends_on:
      - redis_server
      - parser
    ports:
      - "8000:8000"
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 10
        window: 10s

  web_client:
    env_file:
      - ./config/docker.env
    build:
      context: ./web_server/client
      target: release
    image: "transit_data_access/web_client:latest"
    depends_on:
      - web_server
    ports:
      - "80:3000"
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 3
        window: 30s
