version: '3.4'

services:
  redis_server:
    image: redis:5
    ports:
      - "6379:6379"

  parser:
    env_file:
      - ./config/docker.env
    build: ./parser
    image: "farkmarnum/transit_data_access:parser"
    depends_on:
      - redis_server
    ports:
      - "45654:45654"
    deploy:
      resources:
       limits:
        memory: 512M

  web_server:
    env_file:
      - ./config/docker.env
    build:
      context: ./web_server
      target: dev
    image: "farkmarnum/transit_data_access:web_server"
    depends_on:
      - redis_server
      - parser
    ports:
      - "8000:8000"
      - "9229:9229"
    deploy:
      resources:
       limits:
        memory: 512M

  web_client:
    env_file:
      - ./config/docker.env
    build:
      context: ./web_server/client
      target: dev
    volumes:
      - ./web_server/client:/app
    image: "farkmarnum/transit_data_access:web_client"
    depends_on:
      - web_server
    ports:
      - "80:3000"
      - "35729:35729"
    environment:
      - CHOKIDAR_USEPOLLING=true
    deploy:
      resources:
       limits:
        memory: 512M