version: '3.4'

services:
  redis_server:
    image: redis:5
    ports:
      - "6379:6379"

  parser:
    env_file:
      - ./config/docker.env
    build: ./parser
    image: "farkmarnum/transit_data_access:parser"
    depends_on:
      - redis_server
    ports:
      - "45654:45654"

  web_server:
    env_file:
      - ./config/docker.env
    build: ./web_server
    image: "farkmarnum/transit_data_access:web_server"
    depends_on:
      - redis_server
      - parser
    ports:
      - "8000:8000"

  web_client:
    env_file:
      - ./config/docker.env
    build:
      context: ./web_server/client
      target: build
    volumes:
      - './src:/app/src'
      - './public:/app/public'
    image: "farkmarnum/transit_data_access:web_client"
    depends_on:
      - web_server
    ports:
      - "3000:3000"
