version: '3'

services:
  redis_server:
    build: ./redis
    image: "redis:latest"
    ports:
      - "6379:6379"

  parser:
    build: ./parser
    image: "parser:latest"
    depends_on:
      - redis_server
    ports:
      - "45654:45654"
    env_file:
      - config/docker.env
